services:
  app-java:
    build: .
    container_name: crud-app
    ports:
      - "8080:8080"
    env_file:
      - dev.env
      # - prod.env
    networks:
      - faculdade-network

networks:
  faculdade-network:
    driver: bridge